"""
exporter.py — Audit Export Engine for LLMSupervisor.

Responsibilities:
- Accept a structured data dict (from ExecutionReport.to_dict())
- Accept quality signals dict (confidence, risk, notes, summary)
- Generate Markdown audit document
- Convert Markdown data to HTML audit document
- Generate boardroom-ready PDF from HTML/data using reportlab
- Compute SHA-256 integrity hash of execution data
- Write output files to disk

Design:
- All export formats derive from a single internal data model
- Markdown is the base template layer
- HTML is generated from the same data model
- PDF is generated natively via reportlab (no HTML-to-PDF conversion)
- No rich / CLI formatting used here — clean document output only
- no print() calls — raises exceptions on failure
"""

import hashlib
import json
import os
import textwrap
from datetime import datetime
from typing import Any


# ── Public entry point ────────────────────────────────────────────────────── #

def export(
    data: dict[str, Any],
    quality: dict[str, Any],
    fmt: str,
    output_dir: str = ".",
) -> str:
    """
    Export an execution audit report in the requested format.

    Args:
        data:       ExecutionReport.to_dict() output.
        quality:    Dict with keys: confidence_score, risk_level, notes (list), summary (str).
        fmt:        One of: 'md', 'html', 'pdf'
        output_dir: Directory to write the output file. Defaults to current dir.

    Returns:
        Absolute path to the generated file.

    Raises:
        ValueError: If fmt is not a supported format.
        OSError:    If the output directory cannot be created or file cannot be written.
    """
    fmt = fmt.lower().strip()
    if fmt not in ("md", "html", "pdf"):
        raise ValueError(f"Unsupported export format: '{fmt}'. Choose from: md, html, pdf")

    os.makedirs(output_dir, exist_ok=True)

    integrity_hash = _compute_integrity_hash(data)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    execution_id_short = str(data.get("execution_id", "unknown"))[:8]
    base_name = f"audit_{execution_id_short}_{timestamp}"

    if fmt == "md":
        content = _build_markdown(data, quality, integrity_hash)
        out_path = os.path.join(output_dir, f"{base_name}.md")
        _write_text(out_path, content)

    elif fmt == "html":
        content = _build_html(data, quality, integrity_hash)
        out_path = os.path.join(output_dir, f"{base_name}.html")
        _write_text(out_path, content)

    elif fmt == "pdf":
        out_path = os.path.join(output_dir, f"{base_name}.pdf")
        _build_pdf(data, quality, integrity_hash, out_path)

    return os.path.abspath(out_path)


# ── Integrity hash ─────────────────────────────────────────────────────────── #

def _compute_integrity_hash(data: dict[str, Any]) -> str:
    """
    Compute a SHA-256 hash of the execution data dict.

    Serialises the dict to compact, sorted JSON for determinism.
    Returns first 16 hex characters for display (full hash in PDF footer).
    """
    payload = json.dumps(data, sort_keys=True, default=str).encode("utf-8")
    return hashlib.sha256(payload).hexdigest()


# ── Markdown builder ───────────────────────────────────────────────────────── #

def _build_markdown(
    data: dict[str, Any],
    quality: dict[str, Any],
    integrity_hash: str,
) -> str:
    """Build a complete Markdown audit report string."""
    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    confidence = quality.get("confidence_score", "N/A")
    risk = quality.get("risk_level", "N/A")
    notes: list[str] = quality.get("notes", [])
    summary: str = quality.get("summary", "")

    lines = [
        "# AI Execution Audit Report",
        "",
        "> Generated by **LLMSupervisor v0.1.0**",
        "",
        "---",
        "",
        "## Cover",
        "",
        f"| Field              | Value |",
        f"|-------------------|-------|",
        f"| Report Title       | AI Execution Audit Report |",
        f"| Application        | LLMSupervisor |",
        f"| Execution ID       | `{data.get('execution_id', '')}` |",
        f"| Date & Time        | {generated_at} |",
        f"| Model Used         | {data.get('model_name', '')} |",
        f"| Generated By       | LLMSupervisor v0.1.0 |",
        "",
        "---",
        "",
        "## Executive Summary",
        "",
        summary,
        "",
        "---",
        "",
        "## Execution Overview",
        "",
        "| Metric            | Value |",
        "|-------------------|-------|",
        f"| Model             | {data.get('model_name', '')} |",
        f"| Execution Time    | {data.get('execution_time', '')} sec |",
        f"| Input Tokens      | {data.get('input_tokens', ''):,} |",
        f"| Output Tokens     | {data.get('output_tokens', ''):,} |",
        f"| Total Tokens      | {data.get('total_tokens', ''):,} |",
        f"| Estimated Cost    | ${data.get('estimated_cost', 0):.6f} USD |",
        f"| Confidence Score  | {confidence}% |",
        f"| Risk Level        | {risk} |",
        "",
        "---",
        "",
        "## Quality & Risk Assessment",
        "",
    ]

    for note in notes:
        lines.append(f"- {note}")

    lines += [
        "",
        "---",
        "",
        "## Technical Appendix",
        "",
        f"| Field              | Value |",
        f"|-------------------|-------|",
        f"| Execution ID       | `{data.get('execution_id', '')}` |",
        f"| Model              | {data.get('model_name', '')} |",
        f"| Execution Time     | {data.get('execution_time', '')} sec |",
        f"| Input Tokens       | {data.get('input_tokens', '')} |",
        f"| Output Tokens      | {data.get('output_tokens', '')} |",
        f"| Total Tokens       | {data.get('total_tokens', '')} |",
        f"| Estimated Cost     | ${data.get('estimated_cost', 0):.6f} USD |",
        "",
        "---",
        "",
        f"**Report Integrity Hash:** `{integrity_hash}`",
        "",
        f"*Generated at {generated_at} by LLMSupervisor v0.1.0*",
    ]

    return "\n".join(lines)


# ── HTML builder ───────────────────────────────────────────────────────────── #

def _build_html(
    data: dict[str, Any],
    quality: dict[str, Any],
    integrity_hash: str,
) -> str:
    """Build a complete standalone HTML audit report string."""
    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    confidence = quality.get("confidence_score", "N/A")
    risk = quality.get("risk_level", "N/A")
    notes: list[str] = quality.get("notes", [])
    summary: str = quality.get("summary", "")

    confidence_color = "#27ae60" if confidence >= 85 else "#f39c12" if confidence >= 70 else "#e74c3c"
    risk_color = "#27ae60" if risk == "LOW" else "#f39c12"

    notes_html = "\n".join(f"<li>{n}</li>" for n in notes)

    return textwrap.dedent(f"""\
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>AI Execution Audit Report</title>
        <style>
            body {{
                font-family: 'Segoe UI', Arial, sans-serif;
                background: #f4f6f9;
                color: #2c3e50;
                margin: 0;
                padding: 40px;
            }}
            .report {{
                max-width: 860px;
                margin: 0 auto;
                background: #ffffff;
                border-radius: 8px;
                box-shadow: 0 2px 16px rgba(0,0,0,0.10);
                overflow: hidden;
            }}
            .header {{
                background: #1a253c;
                color: #ffffff;
                padding: 32px 40px 24px;
            }}
            .header h1 {{
                margin: 0 0 8px;
                font-size: 22px;
                letter-spacing: 1px;
            }}
            .header .subtitle {{
                font-size: 13px;
                color: #a0b0c8;
            }}
            .section {{
                padding: 28px 40px;
                border-bottom: 1px solid #eaecf0;
            }}
            .section:last-child {{ border-bottom: none; }}
            .section h2 {{
                font-size: 13px;
                text-transform: uppercase;
                letter-spacing: 1.5px;
                color: #7f8c8d;
                margin: 0 0 16px;
            }}
            .summary-box {{
                background: #f0f7ff;
                border-left: 4px solid #2980b9;
                padding: 16px 20px;
                border-radius: 4px;
                font-size: 14px;
                line-height: 1.7;
                color: #2c3e50;
            }}
            table {{
                width: 100%;
                border-collapse: collapse;
                font-size: 14px;
            }}
            th {{
                text-align: left;
                padding: 10px 14px;
                background: #f4f6f9;
                color: #7f8c8d;
                font-weight: 600;
                font-size: 12px;
                text-transform: uppercase;
                letter-spacing: 0.8px;
            }}
            td {{
                padding: 10px 14px;
                border-bottom: 1px solid #f0f0f0;
                color: #2c3e50;
            }}
            tr:last-child td {{ border-bottom: none; }}
            .badge {{
                display: inline-block;
                padding: 3px 10px;
                border-radius: 12px;
                font-size: 12px;
                font-weight: 700;
                color: #fff;
            }}
            .notes-list {{
                list-style: none;
                padding: 0;
                margin: 0;
            }}
            .notes-list li {{
                padding: 6px 0;
                font-size: 14px;
                color: #2c3e50;
                border-bottom: 1px solid #f0f0f0;
            }}
            .notes-list li::before {{
                content: "• ";
                color: #2980b9;
                font-weight: bold;
            }}
            .notes-list li:last-child {{ border-bottom: none; }}
            .footer {{
                background: #f4f6f9;
                padding: 20px 40px;
                font-size: 11px;
                color: #95a5a6;
                text-align: center;
            }}
            code {{
                font-family: 'Courier New', monospace;
                background: #f0f0f0;
                padding: 2px 6px;
                border-radius: 3px;
                font-size: 12px;
                word-break: break-all;
            }}
        </style>
    </head>
    <body>
    <div class="report">

        <div class="header">
            <h1>AI Execution Audit Report</h1>
            <div class="subtitle">LLMSupervisor v0.1.0 &nbsp;|&nbsp; Generated: {generated_at}</div>
        </div>

        <div class="section">
            <h2>Cover</h2>
            <table>
                <tr><th>Field</th><th>Value</th></tr>
                <tr><td>Execution ID</td><td><code>{data.get('execution_id', '')}</code></td></tr>
                <tr><td>Model Used</td><td>{data.get('model_name', '')}</td></tr>
                <tr><td>Date &amp; Time</td><td>{generated_at}</td></tr>
                <tr><td>Generated By</td><td>LLMSupervisor v0.1.0</td></tr>
            </table>
        </div>

        <div class="section">
            <h2>Executive Summary</h2>
            <div class="summary-box">{summary}</div>
        </div>

        <div class="section">
            <h2>Execution Overview</h2>
            <table>
                <tr><th>Metric</th><th>Value</th></tr>
                <tr><td>Model</td><td>{data.get('model_name', '')}</td></tr>
                <tr><td>Execution Time</td><td>{data.get('execution_time', '')} sec</td></tr>
                <tr><td>Input Tokens</td><td>{data.get('input_tokens', 0):,}</td></tr>
                <tr><td>Output Tokens</td><td>{data.get('output_tokens', 0):,}</td></tr>
                <tr><td>Total Tokens</td><td><strong>{data.get('total_tokens', 0):,}</strong></td></tr>
                <tr><td>Estimated Cost</td><td><strong>${data.get('estimated_cost', 0):.6f} USD</strong></td></tr>
                <tr><td>Confidence Score</td><td><span class="badge" style="background:{confidence_color}">{confidence}%</span></td></tr>
                <tr><td>Risk Level</td><td><span class="badge" style="background:{risk_color}">{risk}</span></td></tr>
            </table>
        </div>

        <div class="section">
            <h2>Quality &amp; Risk Assessment</h2>
            <ul class="notes-list">
                {notes_html}
            </ul>
        </div>

        <div class="section">
            <h2>Technical Appendix</h2>
            <table>
                <tr><th>Field</th><th>Value</th></tr>
                <tr><td>Execution ID</td><td><code>{data.get('execution_id', '')}</code></td></tr>
                <tr><td>Model</td><td>{data.get('model_name', '')}</td></tr>
                <tr><td>Input Tokens</td><td>{data.get('input_tokens', '')}</td></tr>
                <tr><td>Output Tokens</td><td>{data.get('output_tokens', '')}</td></tr>
                <tr><td>Total Tokens</td><td>{data.get('total_tokens', '')}</td></tr>
                <tr><td>Estimated Cost</td><td>${data.get('estimated_cost', 0):.6f} USD</td></tr>
            </table>
        </div>

        <div class="footer">
            <strong>Report Integrity Hash:</strong> <code>{integrity_hash}</code><br>
            Generated at {generated_at} by LLMSupervisor v0.1.0
        </div>

    </div>
    </body>
    </html>
    """)


# ── PDF builder ────────────────────────────────────────────────────────────── #

def _build_pdf(
    data: dict[str, Any],
    quality: dict[str, Any],
    integrity_hash: str,
    out_path: str,
) -> None:
    """
    Build a boardroom-ready PDF audit report using reportlab.

    Layout:
        - Dark header bar with title
        - Section blocks with light grey separators
        - Proper font hierarchy (Helvetica family)
        - Page number footer with integrity hash
    """
    try:
        from reportlab.lib import colors
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import mm
        from reportlab.platypus import (
            SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
            HRFlowable, KeepTogether,
        )
        from reportlab.lib.enums import TA_CENTER, TA_LEFT
    except ImportError as exc:
        raise ImportError(
            "reportlab is required for PDF export. "
            "Install it with: pip install reportlab>=4.0.0"
        ) from exc

    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    confidence = quality.get("confidence_score", "N/A")
    risk = quality.get("risk_level", "N/A")
    notes: list[str] = quality.get("notes", [])
    summary: str = quality.get("summary", "")

    # Colour palette
    DARK_BLUE   = colors.HexColor("#1a253c")
    MID_GREY    = colors.HexColor("#7f8c8d")
    LIGHT_GREY  = colors.HexColor("#eaecf0")
    BG_GREY     = colors.HexColor("#f4f6f9")
    GREEN       = colors.HexColor("#27ae60")
    YELLOW      = colors.HexColor("#f39c12")
    RED         = colors.HexColor("#e74c3c")
    WHITE       = colors.white
    BLACK       = colors.HexColor("#2c3e50")

    confidence_color = GREEN if confidence >= 85 else YELLOW if confidence >= 70 else RED
    risk_color = GREEN if risk == "LOW" else YELLOW

    PAGE_W, PAGE_H = A4
    margin = 18 * mm

    styles = getSampleStyleSheet()

    style_body = ParagraphStyle(
        "body", fontName="Helvetica", fontSize=9, textColor=BLACK,
        leading=14, spaceAfter=4,
    )
    style_section_title = ParagraphStyle(
        "section_title", fontName="Helvetica-Bold", fontSize=8,
        textColor=MID_GREY, leading=12, spaceBefore=14, spaceAfter=6,
        textTransform="uppercase",
    )
    style_summary = ParagraphStyle(
        "summary", fontName="Helvetica-Oblique", fontSize=9,
        textColor=BLACK, leading=15, spaceAfter=4,
        leftIndent=8, rightIndent=8,
    )

    # ── Document ──────────────────────────────────────────────────────────── #
    def _on_page(canvas, doc):
        """Draw header bar and footer on every page."""
        canvas.saveState()

        # Header bar
        canvas.setFillColor(DARK_BLUE)
        canvas.rect(0, PAGE_H - 28 * mm, PAGE_W, 28 * mm, fill=1, stroke=0)
        canvas.setFillColor(WHITE)
        canvas.setFont("Helvetica-Bold", 13)
        canvas.drawCentredString(PAGE_W / 2, PAGE_H - 14 * mm, "AI Execution Audit Report")
        canvas.setFont("Helvetica", 8)
        canvas.setFillColor(colors.HexColor("#a0b0c8"))
        canvas.drawCentredString(PAGE_W / 2, PAGE_H - 21 * mm,
                                 f"LLMSupervisor v0.1.0  |  {generated_at}")

        # Footer
        canvas.setFillColor(BG_GREY)
        canvas.rect(0, 0, PAGE_W, 18 * mm, fill=1, stroke=0)
        canvas.setFillColor(MID_GREY)
        canvas.setFont("Helvetica", 7)
        canvas.drawString(margin, 11 * mm,
                          f"Integrity Hash: {integrity_hash[:32]}...")
        canvas.drawRightString(PAGE_W - margin, 11 * mm,
                               f"Page {doc.page}")
        canvas.setFillColor(LIGHT_GREY)
        canvas.rect(margin, 15 * mm, PAGE_W - 2 * margin, 0.3 * mm, fill=1, stroke=0)

        canvas.restoreState()

    doc = SimpleDocTemplate(
        out_path,
        pagesize=A4,
        leftMargin=margin,
        rightMargin=margin,
        topMargin=32 * mm,
        bottomMargin=22 * mm,
        title="AI Execution Audit Report",
        author="LLMSupervisor v0.1.0",
    )

    def _section(title: str) -> list:
        return [
            HRFlowable(width="100%", thickness=0.5, color=LIGHT_GREY,
                       spaceAfter=2, spaceBefore=10),
            Paragraph(title, style_section_title),
        ]

    def _table(rows: list, col_widths=None) -> Table:
        t = Table(rows, colWidths=col_widths or [70 * mm, None])
        t.setStyle(TableStyle([
            ("BACKGROUND",  (0, 0), (-1, 0), BG_GREY),
            ("TEXTCOLOR",   (0, 0), (-1, 0), MID_GREY),
            ("FONTNAME",    (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE",    (0, 0), (-1, 0), 7.5),
            ("FONTNAME",    (0, 1), (-1, -1), "Helvetica"),
            ("FONTSIZE",    (0, 1), (-1, -1), 9),
            ("TEXTCOLOR",   (0, 1), (-1, -1), BLACK),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [WHITE, BG_GREY]),
            ("GRID",        (0, 0), (-1, -1), 0.3, LIGHT_GREY),
            ("TOPPADDING",  (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ]))
        return t

    story = []

    # ── Cover ─────────────────────────────────────────────────────────────── #
    story += _section("Cover")
    story.append(_table([
        ["Field", "Value"],
        ["Execution ID",    str(data.get("execution_id", ""))],
        ["Model Used",      str(data.get("model_name", ""))],
        ["Date & Time",     generated_at],
        ["Generated By",    "LLMSupervisor v0.1.0"],
    ]))
    story.append(Spacer(1, 4 * mm))

    # ── Executive Summary ─────────────────────────────────────────────────── #
    story += _section("Executive Summary")
    story.append(Paragraph(summary, style_summary))
    story.append(Spacer(1, 4 * mm))

    # ── Execution Overview ────────────────────────────────────────────────── #
    story += _section("Execution Overview")
    story.append(_table([
        ["Metric", "Value"],
        ["Model",           str(data.get("model_name", ""))],
        ["Execution Time",  f"{data.get('execution_time', '')} sec"],
        ["Input Tokens",    f"{data.get('input_tokens', 0):,}"],
        ["Output Tokens",   f"{data.get('output_tokens', 0):,}"],
        ["Total Tokens",    f"{data.get('total_tokens', 0):,}"],
        ["Estimated Cost",  f"${data.get('estimated_cost', 0):.6f} USD"],
        ["Confidence Score", f"{confidence}%"],
        ["Risk Level",      str(risk)],
    ]))
    story.append(Spacer(1, 4 * mm))

    # ── Quality & Risk ────────────────────────────────────────────────────── #
    story += _section("Quality & Risk Assessment")
    for note in notes:
        story.append(Paragraph(f"• {note}", style_body))
    story.append(Spacer(1, 4 * mm))

    # ── Technical Appendix ───────────────────────────────────────────────── #
    story += _section("Technical Appendix")
    story.append(_table([
        ["Field", "Value"],
        ["Execution ID",   str(data.get("execution_id", ""))],
        ["Model",          str(data.get("model_name", ""))],
        ["Input Tokens",   str(data.get("input_tokens", ""))],
        ["Output Tokens",  str(data.get("output_tokens", ""))],
        ["Total Tokens",   str(data.get("total_tokens", ""))],
        ["Estimated Cost", f"${data.get('estimated_cost', 0):.6f} USD"],
    ]))
    story.append(Spacer(1, 6 * mm))

    # ── Integrity hash ────────────────────────────────────────────────────── #
    story.append(HRFlowable(width="100%", thickness=0.5, color=LIGHT_GREY,
                            spaceAfter=4, spaceBefore=6))
    story.append(Paragraph(
        f"<font size='7' color='#7f8c8d'>"
        f"<b>Report Integrity Hash:</b> {integrity_hash}</font>",
        style_body,
    ))

    doc.build(story, onFirstPage=_on_page, onLaterPages=_on_page)


# ── File writer ────────────────────────────────────────────────────────────── #

def _write_text(path: str, content: str) -> None:
    """Write a UTF-8 text file."""
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(content)
