"""
report.py — ExecutionReport dataclass and CLI display logic.

Responsibilities:
- Define ExecutionReport data structure (all per-execution metrics)
- Compute quality signals: confidence score, risk level, system notes
- Render rich CLI audit panel (display())
- Delegate export to exporter module
- Provide stable to_dict() serialisation

Hallucination analysis is attached externally by the auditor layer.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Tuple, Union

from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich.text import Text
from rich import box

_console = Console()


@dataclass
class ExecutionReport:
    """
    Immutable record of a single LLM execution with comprehensive audit trail.

    This dataclass contains all metrics and metadata for a single LLM execution,
    including token usage, cost estimation, quality assessment, governance
    compliance, and optional hallucination analysis.

    Attributes
    ----------
    execution_id : str
        Unique identifier for this execution (UUID format).
    model_name : str
        Name of the LLM model used (e.g., "gpt-4o-mini", "claude-3-sonnet").
    execution_time : float
        Time taken to execute the LLM call in seconds.
    input_tokens : int
        Number of tokens in the input/prompt sent to the model.
    output_tokens : int
        Number of tokens in the response generated by the model.
    total_tokens : int
        Sum of input_tokens and output_tokens.
    estimated_cost : float
        Estimated cost of the execution in USD based on model pricing.
    raw_response : str
        Raw text response returned by the LLM.
    ai_summary : Optional[str]
        AI-generated executive summary of the execution (if enabled).
    warnings : List[str]
        List of governance warnings (budget, guard mode violations).
    hallucination : Optional[object]
        Hallucination analysis result (HallucinationAnalysis instance).

    Methods
    -------
    display()
        Render a rich CLI audit panel showing all metrics and analysis.
    export(fmt="md", output_dir=".")
        Export the report to a file in markdown, HTML, or PDF format.
    to_dict()
        Convert the report to a dictionary for serialization.

    Notes
    -----
    Core fields (execution_id through raw_response) are set at construction
    by LLMAuditor. Quality signals (confidence, risk, notes) are computed
    on demand. Hallucination analysis is attached after construction.

    The report is designed to be immutable after creation to ensure audit
    trail integrity.

    Examples
    --------
    Display an execution report:

    >>> report.display()
    # Shows rich CLI panel with all metrics

    Export to different formats:

    >>> path = report.export("pdf", "./reports")
    >>> print(f"Report saved to: {path}")

    Access metrics programmatically:

    >>> print(f"Cost: ${report.estimated_cost:.4f}")
    >>> print(f"Tokens: {report.total_tokens}")
    """

    # ── Core metrics (required at construction) ─────────────────────────── #
    execution_id:   str
    model_name:     str
    execution_time: float
    input_tokens:   int
    output_tokens:  int
    total_tokens:   int
    estimated_cost: float
    raw_response:   str

    # ── Optional fields (post-construction injection) ─────────────────────── #
    ai_summary: Optional[str] = field(default=None, compare=False, repr=False)

    # Governance warnings (populated by observe/execute in alert mode)
    warnings: List[str] = field(default_factory=list, compare=False, repr=False)

    # Hallucination analysis result (attached by auditor after hallucination detection)
    hallucination: Optional[Any] = field(default=None, compare=False, repr=False)

    # ── Public display ────────────────────────────────────────────────────── #

    def display(self) -> None:
        """
        Render a structured CLI audit panel using Rich formatting.

        Displays a comprehensive audit report in the terminal including:
        - Model information and execution metadata
        - Token usage and cost estimation
        - Quality metrics (confidence score, risk level)
        - Hallucination analysis results (if available)
        - Governance warnings (if any)
        - AI-generated executive summary

        The display uses Rich library for professional formatting with
        colors, tables, and structured layout.

        Notes
        -----
        This method is designed to be safe and will never crash the host
        application. If any display error occurs, it will either show a
        minimal error message or fail silently.

        The display includes computed quality signals that are calculated
        on-demand when this method is called.

        Examples
        --------
        Display execution audit:

        >>> report = auditor.execute(...)
        >>> report.display()
        # Shows formatted audit panel in terminal
        """
        try:
            self._display_impl()
        except Exception as exc:
            try:
                _console.print(f"[dim red]LLMAuditor display error: {exc}[/dim red]")
            except Exception:
                pass  # absolute last resort — never crash the host app

    def _display_impl(self) -> None:
        """Internal display logic (separated for error isolation)."""
        confidence_score, confidence_label = self._compute_confidence()
        risk_level, risk_label = self._compute_risk()
        notes = self._generate_notes()
        summary = self._generate_summary()

        header_text = Text(
            "LLM AUDITOR  ·  EXECUTION REPORT",
            style="bold white on navy_blue",
            justify="center",
        )

        # Model Info
        model_table = Table(box=box.SIMPLE, show_header=False, padding=(0, 1))
        model_table.add_column(style="dim cyan", no_wrap=True)
        model_table.add_column(style="white")
        model_table.add_row("Execution ID", self.execution_id)
        model_table.add_row("Model", self.model_name)
        model_table.add_row("Execution Time", f"{self.execution_time} sec")

        # Usage Metrics
        usage_table = Table(box=box.SIMPLE, show_header=False, padding=(0, 1))
        usage_table.add_column(style="dim cyan", no_wrap=True)
        usage_table.add_column(style="white")
        usage_table.add_row("Input Tokens",  f"{self.input_tokens:,}")
        usage_table.add_row("Output Tokens", f"{self.output_tokens:,}")
        usage_table.add_row("Total Tokens",  f"[bold]{self.total_tokens:,}[/bold]")
        usage_table.add_row("Estimated Cost", f"[bold green]${self.estimated_cost:.6f} USD[/bold green]")

        # Quality Metrics
        conf_color = "green" if confidence_score >= 85 else "yellow" if confidence_score >= 70 else "red"
        risk_color = "green" if risk_level == "LOW" else "yellow"

        quality_table = Table(box=box.SIMPLE, show_header=False, padding=(0, 1))
        quality_table.add_column(style="dim cyan", no_wrap=True)
        quality_table.add_column()
        quality_table.add_row(
            "Confidence Score",
            f"[bold {conf_color}]{confidence_score}%[/bold {conf_color}]  {confidence_label}",
        )
        quality_table.add_row(
            "Risk Level",
            f"[bold {risk_color}]{risk_level}[/bold {risk_color}]  {risk_label}",
        )

        # Hallucination metrics (if available)
        if self.hallucination is not None:
            hal = self.hallucination
            hal_color = "green" if hal.risk_level == "LOW" else "yellow" if hal.risk_level == "MEDIUM" else "red"
            quality_table.add_row(
                "Hallucination Risk",
                f"[bold {hal_color}]{hal.risk_score_pct}% {hal.risk_level}[/bold {hal_color}]  ({hal.method})",
            )

        # System Notes
        notes_text = Text()
        for i, note in enumerate(notes):
            notes_text.append(f"  \u2022 {note}", style="dim white")
            if i < len(notes) - 1:
                notes_text.append("\n")

        from rich.console import Group

        content_parts = [
            header_text,
            "",
            "[bold dim]MODEL INFO[/bold dim]",
            model_table,
            "[bold dim]USAGE METRICS[/bold dim]",
            usage_table,
            "[bold dim]QUALITY METRICS[/bold dim]",
            quality_table,
            "[bold dim]SYSTEM NOTES[/bold dim]",
            notes_text,
        ]

        # Governance Warnings
        if self.warnings:
            warnings_text = Text()
            for i, warning in enumerate(self.warnings):
                warnings_text.append(f"  \u26a0  {warning}", style="bold yellow")
                if i < len(self.warnings) - 1:
                    warnings_text.append("\n")
            content_parts += ["", "[bold yellow]GOVERNANCE WARNINGS[/bold yellow]", warnings_text]

        # Executive Summary
        display_summary = self.ai_summary or summary
        summary_text = Text(f"\n  {display_summary}\n", style="italic white")
        content_parts += ["", "[bold dim]AI EXECUTIVE SUMMARY[/bold dim]", summary_text]

        _console.print(
            Panel(Group(*content_parts), border_style="navy_blue", padding=(1, 2))
        )

    # ── Export ────────────────────────────────────────────────────────────── #

    def export(self, fmt: str = "md", output_dir: str = ".") -> str:
        """
        Export this execution report to a file.

        Generates a formatted report file containing all execution metrics,
        quality assessment, governance compliance, and analysis results.

        Parameters
        ----------
        fmt : str, default="md"
            Output format. Supported formats:
            - "md" : Markdown format
            - "html" : HTML format  
            - "pdf" : PDF format
        output_dir : str, default="."
            Directory path where the report file will be saved.
            Directory will be created if it doesn't exist.

        Returns
        -------
        str
            Path to the exported report file, or error message if export failed.

        Notes
        -----
        The export includes:
        - All execution metrics (tokens, cost, timing)
        - Quality assessment (confidence score, risk level)
        - Hallucination analysis results (if available)
        - Governance warnings (if any)
        - System notes and recommendations
        - Executive summary

        Export is designed to be safe and will return error messages
        rather than raise exceptions if export fails.

        Examples
        --------
        Export to different formats:

        >>> pdf_path = report.export("pdf", "./reports")
        >>> html_path = report.export("html", "./web_reports")
        >>> md_path = report.export("md")  # Current directory
        """
        try:
            from llmauditor.exporter import export_execution

            confidence_score, confidence_label = self._compute_confidence()
            risk_level, _ = self._compute_risk()
            notes = self._generate_notes()
            summary = self._generate_summary()

            quality = {
                "confidence_score": confidence_score,
                "risk_level": risk_level,
                "notes": notes,
                "summary": summary,
            }

            return export_execution(
                data=self.to_dict(),
                quality=quality,
                fmt=fmt,
                output_dir=output_dir,
            )
        except Exception as exc:
            return f"Export failed: {exc}"

    # ── Serialisation ─────────────────────────────────────────────────────── #

    def to_dict(self) -> Dict[str, Any]:
        """
        Convert the execution report to a dictionary for serialization.

        Returns
        -------
        Dict[str, Any]
            Dictionary containing all report fields and metadata.
            Includes execution metrics, quality signals, governance
            warnings, and hallucination analysis (if available).

        Notes
        -----
        The returned dictionary includes:
        - All core execution metrics
        - Computed quality signals (confidence, risk level)
        - Governance warnings list
        - Hallucination analysis results (if attached)
        - AI summary (if generated)

        This method is used internally for export functionality
        and external integrations requiring structured data.

        Examples
        --------
        Get report as structured data:

        >>> data = report.to_dict()
        >>> print(f"Model: {data['model_name']}")
        >>> print(f"Cost: ${data['estimated_cost']:.4f}")
        """
        try:
            confidence_score, confidence_label = self._compute_confidence()
            risk_level, risk_label = self._compute_risk()

            d = {
                "execution_id":     self.execution_id,
                "model_name":       self.model_name,
                "execution_time":   self.execution_time,
                "input_tokens":     self.input_tokens,
                "output_tokens":    self.output_tokens,
                "total_tokens":     self.total_tokens,
                "estimated_cost":   self.estimated_cost,
                "confidence_score": confidence_score,
                "confidence_label": confidence_label,
                "risk_level":       risk_level,
                "risk_label":       risk_label,
                "warnings":         list(self.warnings),
            }

            if self.hallucination is not None:
                try:
                    d["hallucination"] = self.hallucination.to_dict()
                except Exception:
                    d["hallucination"] = {"error": "serialisation failed"}

            return d
        except Exception:
            # Absolute minimum — enough for downstream code to not crash
            return {
                "execution_id": getattr(self, "execution_id", "unknown"),
                "model_name": getattr(self, "model_name", "unknown"),
                "execution_time": 0, "input_tokens": 0, "output_tokens": 0,
                "total_tokens": 0, "estimated_cost": 0,
                "confidence_score": 0, "risk_level": "UNKNOWN",
                "warnings": ["to_dict serialisation error"],
            }

    # ── Private quality computers ──────────────────────────────────────────── #

    def _compute_confidence(self) -> tuple[int, str]:
        """Compute confidence score (0–100) and label."""
        score = 100

        if len(self.raw_response) < 20:
            score -= 30
        elif len(self.raw_response) < 50:
            score -= 15

        if self.estimated_cost > 0.05:
            score -= 20
        elif self.estimated_cost > 0.02:
            score -= 10

        if self.execution_time > 10:
            score -= 15
        elif self.execution_time > 5:
            score -= 5

        score = max(0, score)

        if score >= 85:
            label = "High \u2014 execution completed within expected parameters"
        elif score >= 70:
            label = "Medium \u2014 minor anomalies detected, review advised"
        else:
            label = "Low \u2014 significant anomalies detected, manual review required"

        return score, label

    def _compute_risk(self) -> tuple[str, str]:
        """Compute risk level (LOW / MEDIUM / HIGH) and label."""
        if self.estimated_cost > 0.05 or self.total_tokens > 8000:
            return "HIGH", "High usage detected \u2014 consider rate limiting or token budgets"
        if self.estimated_cost > 0.01 or self.total_tokens > 3000:
            return "MEDIUM", "Moderate usage \u2014 monitor cumulative cost across sessions"
        return "LOW", "Within normal operating parameters"

    def _generate_notes(self) -> list[str]:
        """Generate clinical system notes from execution metrics."""
        notes = []

        if self.execution_time > 10:
            notes.append(f"Execution time {self.execution_time}s exceeds 10s threshold.")
        elif self.execution_time > 5:
            notes.append(f"Execution time {self.execution_time}s is elevated.")
        else:
            notes.append(f"Execution time {self.execution_time}s is within normal range.")

        if self.total_tokens > 8000:
            notes.append(f"Token usage {self.total_tokens:,} is very high.")
        elif self.total_tokens > 3000:
            notes.append(f"Token usage {self.total_tokens:,} is moderate.")
        else:
            notes.append(f"Token usage {self.total_tokens:,} is efficient.")

        if self.estimated_cost > 0.05:
            notes.append(f"Cost ${self.estimated_cost:.6f} USD is above the high-cost threshold.")
        elif self.estimated_cost > 0.01:
            notes.append(f"Cost ${self.estimated_cost:.6f} USD is moderate.")
        else:
            notes.append(f"Cost ${self.estimated_cost:.6f} USD is within budget norms.")

        if len(self.raw_response) < 20:
            notes.append("Response is very short \u2014 possible refusal or truncation.")

        return notes

    def _generate_summary(self) -> str:
        """Generate a rule-based executive summary."""
        if self.ai_summary:
            return self.ai_summary

        confidence_score, _ = self._compute_confidence()
        risk_level, _ = self._compute_risk()

        quality = (
            "satisfactory" if confidence_score >= 85
            else "adequate" if confidence_score >= 70
            else "concerning"
        )
        risk_note = (
            "within normal operating parameters" if risk_level == "LOW"
            else "flagged for elevated resource usage" if risk_level == "MEDIUM"
            else "flagged as high-risk and requires immediate review"
        )

        return (
            f"This execution of {self.model_name} completed in {self.execution_time}s, "
            f"consuming {self.total_tokens:,} tokens at an estimated cost of "
            f"${self.estimated_cost:.6f} USD. "
            f"Overall confidence is {quality} ({confidence_score}%), "
            f"and the execution risk profile is {risk_note}."
        )
